version: '3.7'

# Define services
services:
  # Database Service (Mysql)
  mysql-db:
    container_name: mysql-db
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  # App backend service
  spring-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
